// Smdn.Fundamental.String.Replacement.dll (Smdn.Fundamental.String.Replacement-3.0.2)
//   Name: Smdn.Fundamental.String.Replacement
//   AssemblyVersion: 3.0.2.0
//   InformationalVersion: 3.0.2+9805a70fc9d7e01ace74c4db2ba31bb729f9e567
//   TargetFramework: .NETCoreApp,Version=v6.0
//   Configuration: Release
//   Referenced assemblies:
//     System.Memory, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
//     System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
#nullable enable annotations

using Smdn;

namespace Smdn {
  public delegate string? ReplaceCharEvaluator(char ch, string str, int index);
  public delegate string? ReplaceStringEvaluator(string matched, string str, int index);

  public static class StringReplacementExtensions {
    public static string Remove(this string str, params string[] oldValues) {}
    public static string RemoveChars(this string str, params char[] oldChars) {}
    public static string Replace(this string str, char[] oldChars, ReplaceCharEvaluator evaluator) {}
    public static string Replace(this string str, string[] oldValues, ReplaceStringEvaluator evaluator) {}
  }
}
// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.1.7.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.2.0.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
