// Smdn.Test.NUnit.Utils.dll (Smdn.Test.NUnit.Utils-4.1.0)
//   Name: Smdn.Test.NUnit.Utils
//   AssemblyVersion: 4.1.0.0
//   InformationalVersion: 4.1.0+a2b810f485a890f0e99bf4b9ebe92881f4f71824
//   TargetFramework: .NETFramework,Version=v4.6.2
//   Configuration: Release
//   Referenced assemblies:
//     System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
//     System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
//     mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
//     nunit.framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb
//     nunit.framework.legacy, Version=4.0.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb

using System;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using NUnit.Framework.Legacy;

namespace Smdn.Test.NUnit {
  public static class Encodings {
    public static Encoding EucJP { get; }
    public static Encoding Jis { get; }
    public static Encoding Latin1 { get; }
    public static Encoding ShiftJis { get; }
  }

  public static class IOUtils {
    public static void UsingCurrentDirectory(string path, Action action) {}
    public static async Task UsingCurrentDirectoryAsync(string path, Func<Task> action) {}
    public static void UsingDirectory(string path, Action<DirectoryInfo> action) {}
    public static void UsingDirectory(string path, bool ensureDirectoryCreated, Action<DirectoryInfo> action) {}
    public static Task UsingDirectoryAsync(string path, Func<DirectoryInfo, Task> action) {}
    public static async Task UsingDirectoryAsync(string path, bool ensureDirectoryCreated, Func<DirectoryInfo, Task> action) {}
    public static void UsingFile(string path, Action<FileInfo> action) {}
    public static async Task UsingFileAsync(string path, Func<FileInfo, Task> action) {}
  }
}

namespace Smdn.Test.NUnit.Assertion {
  public class Assert : ClassicAssert {
    public static void Elapses(TimeSpan expected, TestDelegate code, string message = null) {}
    public static void ElapsesAsync(TimeSpan expected, AsyncTestDelegate code, string message = null) {}
    public static void ElapsesInRange(TimeSpan expectedMin, TimeSpan expectedMax, TestDelegate code, string message = null) {}
    public static void ElapsesInRangeAsync(TimeSpan expectedMin, TimeSpan expectedMax, AsyncTestDelegate code, string message = null) {}
    public static void IsSerializable<TSerializable>(TSerializable obj, Action<TSerializable> testDeserializedObject = null) {}
    public static void IsSerializable<TSerializable>(TSerializable obj, IFormatter serializationFormatter, IFormatter deserializationFormatter, Action<TSerializable> testDeserializedObject = null) {}
    public static void NotElapse(TimeSpan expected, TestDelegate code, string message = null) {}
    public static void NotElapseAsync(TimeSpan expected, AsyncTestDelegate code, string message = null) {}
    public static TException ThrowsOrAggregates<TException>(TestDelegate code) where TException : Exception {}

    public Assert() {}
  }
}
// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.4.1.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.3.1.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
