// Smdn.Test.NUnit.Utils.dll (Smdn.Test.NUnit.Utils-5.0.0)
//   Name: Smdn.Test.NUnit.Utils
//   AssemblyVersion: 5.0.0.0
//   InformationalVersion: 5.0.0+34752c83c416101b818cb6d906f9a612519ebd59
//   TargetFramework: .NETCoreApp,Version=v10.0
//   Configuration: Release
//   Metadata: IsTrimmable=True
//   Metadata: RepositoryUrl=https://github.com/smdn/Smdn.Fundamentals
//   Metadata: RepositoryBranch=main
//   Metadata: RepositoryCommit=34752c83c416101b818cb6d906f9a612519ebd59
//   Referenced assemblies:
//     System.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Text.Encoding.CodePages, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Threading.Thread, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     nunit.framework, Version=5.0.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb
//     nunit.framework.legacy, Version=5.0.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb
#nullable enable annotations

using System;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework.Legacy;

namespace Smdn.Test.NUnit {
  public static class Encodings {
    public static Encoding? EucJP { get; }
    public static Encoding? Jis { get; }
    public static Encoding Latin1 { get; }
    public static Encoding? ShiftJis { get; }
  }

  public static class IOUtils {
    public static void UsingCurrentDirectory(string path, Action action) {}
    public static async Task UsingCurrentDirectoryAsync(string path, Func<Task> action) {}
    public static void UsingDirectory(string path, Action<DirectoryInfo> action) {}
    public static void UsingDirectory(string path, bool ensureDirectoryCreated, Action<DirectoryInfo> action) {}
    public static Task UsingDirectoryAsync(string path, Func<DirectoryInfo, Task> action) {}
    public static async Task UsingDirectoryAsync(string path, bool ensureDirectoryCreated, Func<DirectoryInfo, Task> action) {}
    public static void UsingFile(string path, Action<FileInfo> action) {}
    public static async Task UsingFileAsync(string path, Func<FileInfo, Task> action) {}
  }
}

namespace Smdn.Test.NUnit.Assertion {
  public class Assert : ClassicAssert {
    public static void Elapses(TimeSpan expected, Action code, string? message = null) {}
    public static void ElapsesAsync(TimeSpan expected, Func<Task> code, string? message = null) {}
    public static void ElapsesInRange(TimeSpan expectedMin, TimeSpan expectedMax, Action code, string? message = null) {}
    public static void ElapsesInRangeAsync(TimeSpan expectedMin, TimeSpan expectedMax, Func<Task> code, string? message = null) {}
    public static void IsSerializable<TSerializable>(TSerializable obj, Action<TSerializable>? testDeserializedObject = null) {}
    public static void NotElapse(TimeSpan expected, Action code, string? message = null) {}
    public static void NotElapseAsync(TimeSpan expected, Func<Task> code, string? message = null) {}

    public Assert() {}
  }
}
// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.8.2.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.6.2.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
