// Smdn.Null.dll (Smdn.Null-1.0.0)
//   Name: Smdn.Null
//   AssemblyVersion: 1.0.0.0
//   InformationalVersion: 1.0.0+e8af51513c4e44dbde3f51c3db367be69d24375c
//   TargetFramework: 
//   Configuration: Release
//   Referenced assemblies:
//     System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.1.7.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.2.0.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
