// Smdn.Null.dll (Smdn.Null-1.0.0)
//   Name: Smdn.Null
//   AssemblyVersion: 1.0.0.0
//   InformationalVersion: 1.0.0+472b5ed1aeeffc8cd8a454fe12978f70be2e5c41
//   TargetFramework: .NETStandard,Version=v1.0
//   Configuration: Release
//   Referenced assemblies:
//     System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.1.7.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.2.0.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
