// Smdn.Null.dll (Smdn.Null-1.0.0-preview1)
//   Name: Smdn.Null
//   AssemblyVersion: 1.0.0.0
//   InformationalVersion: 1.0.0-preview1+23b4b1d46d98420c2d12a05e55a2bf52bc6cb75a
//   TargetFramework: 
//   Configuration: Release
//   Referenced assemblies:
//     System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.2.1.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.2.0.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
