// SPDX-FileCopyrightText: 2022 smdn <smdn@smdn.jp>
// SPDX-License-Identifier: MIT
using System;
#if NULL_STATE_STATIC_ANALYSIS_ATTRIBUTES
using System.Diagnostics.CodeAnalysis;
#endif
using System.Linq;
using System.Reflection;

using Smdn.Reflection.Attributes;

namespace Smdn.Reflection;

public static class FieldInfoExtensions {
  private static BindingFlags GetBindingFlagsForAutoGeneratedMember(FieldInfo f)
    => (f.IsStatic ? BindingFlags.Static : BindingFlags.Instance) | BindingFlags.Public | BindingFlags.NonPublic;

  private static bool IsAutoGeneratedField(FieldInfo f)
    => f.HasCompilerGeneratedAttribute();

  public static bool IsPropertyBackingField(this FieldInfo f)
    => TryGetPropertyFromBackingField(
      f ?? throw new ArgumentNullException(nameof(f)),
      out _
    );

  public static bool TryGetPropertyFromBackingField(
    this FieldInfo backingField,
#if NULL_STATE_STATIC_ANALYSIS_ATTRIBUTES
    [NotNullWhen(true)]
#endif
    out PropertyInfo? property
  )
  {
    property = default;

    if (
      backingField is null ||
      !IsAutoGeneratedField(backingField) ||
      backingField.DeclaringType is null
    ) {
      return false;
    }

    var propertyName = PropertyInfoExtensions.GetPropertyNameFromBackingField(backingField);

    if (propertyName is null)
      return false;

    var mayBeAutoGeneratedProperty = backingField.DeclaringType.GetProperty(
      name: propertyName,
      bindingAttr: GetBindingFlagsForAutoGeneratedMember(backingField)
    );

    if (
      mayBeAutoGeneratedProperty is not null &&
      PropertyInfoExtensions.IsAccessorAutoGenerated(mayBeAutoGeneratedProperty)
    ) {
      property = mayBeAutoGeneratedProperty;
      return true;
    }

    return false;
  }

  public static bool IsEventBackingField(this FieldInfo f)
    => TryGetEventFromBackingField(
      f ?? throw new ArgumentNullException(nameof(f)),
      out _
    );

  public static bool TryGetEventFromBackingField(
    this FieldInfo backingField,
#if NULL_STATE_STATIC_ANALYSIS_ATTRIBUTES
    [NotNullWhen(true)]
#endif
    out EventInfo? ev
  )
  {
    ev = null;

    if (
      backingField is null ||
      !IsAutoGeneratedField(backingField) ||
      backingField.DeclaringType is null
    ) {
      return false;
    }

    var mayBeAutoGeneratedEvent = backingField.DeclaringType.GetEvent(
      name: EventInfoExtensions.GetEventNameFromBackingField(backingField),
      bindingAttr: GetBindingFlagsForAutoGeneratedMember(backingField)
    );

    if (mayBeAutoGeneratedEvent is not null && EventInfoExtensions.IsAccessorAutoGenerated(mayBeAutoGeneratedEvent)) {
      ev = mayBeAutoGeneratedEvent;
      return true;
    }

    return false;
  }

  public static bool IsReadOnly(this FieldInfo f)
    => f is null
      ? throw new ArgumentNullException(nameof(f))
      : f.HasIsReadOnlyAttribute();

  /// <seealso href="https://learn.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-11.0/required-members">
  /// Feature specifications - Required Members
  /// </seealso>
  public static bool IsRequired(this FieldInfo f)
  {
    if (f is null)
      throw new ArgumentNullException(nameof(f));

    // following modifiers cannot be combined with `required`
    if (f.IsStatic) // `static`
      return false;
    if (f.IsInitOnly) // `readonly`
      return false;
    if (f.IsLiteral) // `const`
      return false;
    if (f.FieldType.IsByRef) // `ref` and `ref readonly`
      return false;

    return f.HasRequiredMemberAttribute();
  }

  public static bool IsFixedBuffer(this FieldInfo f)
    => TryGetFixedBufferElementTypeAndLengthCore(
      field: f ?? throw new ArgumentNullException(nameof(f)),
      getConstructorArgs: false,
      out _,
      out _
    );

  public static bool TryGetFixedBufferElementTypeAndLength(
    this FieldInfo f,
#if NULL_STATE_STATIC_ANALYSIS_ATTRIBUTES
    [NotNullWhen(true)]
#endif
    out Type? elementType,
    out int length
  )
    => TryGetFixedBufferElementTypeAndLengthCore(
      field: f ?? throw new ArgumentNullException(nameof(f)),
      getConstructorArgs: true,
      elementType: out elementType,
      length: out length
    );

  private static bool TryGetFixedBufferElementTypeAndLengthCore(
    FieldInfo field,
    bool getConstructorArgs,
#if NULL_STATE_STATIC_ANALYSIS_ATTRIBUTES
    [NotNullWhen(true)]
#endif
    out Type? elementType,
    out int length
  )
  {
    elementType = default;
    length = default;

    if (field.IsStatic)
      return false;
    if (field.IsInitOnly)
      return false;
    if (field.IsLiteral)
      return false;

    var attrFixedBuffer = field
      .GetCustomAttributesData()
      .FirstOrDefault(
        static d => string.Equals(
          typeof(System.Runtime.CompilerServices.FixedBufferAttribute).FullName,
          d.AttributeType.FullName,
          StringComparison.Ordinal
        )
      );

    var hasFixedBufferAttribute = attrFixedBuffer is not null;

    if (hasFixedBufferAttribute && getConstructorArgs) {
#if SYSTEM_INDEX
      if (attrFixedBuffer!.ConstructorArguments is [var argElementType, var argLength]) {
#else
      if (attrFixedBuffer!.ConstructorArguments.Count == 2) {
        var argElementType = attrFixedBuffer.ConstructorArguments[0];
        var argLength = attrFixedBuffer.ConstructorArguments[1];
#endif
        if (
          string.Equals(typeof(Type).FullName, argElementType.ArgumentType.FullName, StringComparison.Ordinal) &&
          argElementType.Value is Type argElementTypeValue
        ) {
          elementType = argElementTypeValue;
        }
        else {
          hasFixedBufferAttribute = false; // has an unexpected arg
        }

        if (
          string.Equals(typeof(int).FullName, argLength.ArgumentType.FullName, StringComparison.Ordinal) &&
          argLength.Value is int argLengthValue
        ) {
          length = argLengthValue;
        }
        else {
          hasFixedBufferAttribute = false; // has an unexpected arg
        }
      }
      else {
        hasFixedBufferAttribute = false; // has unexpected args
      }
    }

    return hasFixedBufferAttribute;
  }
}
