// Smdn.Fundamental.Encoding.dll (Smdn.Fundamental.Encoding-3.1.0)
//   Name: Smdn.Fundamental.Encoding
//   AssemblyVersion: 3.1.0.0
//   InformationalVersion: 3.1.0+2d806cd6c16472e5eb06285f0d7c26cd69fb45fa
//   TargetFramework: .NETCoreApp,Version=v10.0
//   Configuration: Release
//   Metadata: IsTrimmable=True
//   Metadata: IsAotCompatible=True
//   Metadata: RepositoryUrl=https://github.com/smdn/Smdn.Fundamentals
//   Metadata: RepositoryBranch=main
//   Metadata: RepositoryCommit=2d806cd6c16472e5eb06285f0d7c26cd69fb45fa
//   Referenced assemblies:
//     System.Collections, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Collections.Immutable, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Memory, Version=10.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
//     System.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.Serialization;
using System.Text;
using Smdn.Text.Encodings;

namespace Smdn.Text.Encodings {
  [TypeForwardedFrom("Smdn, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null")]
  public delegate Encoding? EncodingSelectionCallback(string name);

  [TypeForwardedFrom("Smdn, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null")]
  [Serializable]
  public class EncodingNotSupportedException : NotSupportedException {
    [Obsolete("SYSLIB0051: Legacy serialization support APIs are obsolete")]
    protected EncodingNotSupportedException(SerializationInfo info, StreamingContext context) {}
    public EncodingNotSupportedException() {}
    public EncodingNotSupportedException(string encodingName) {}
    public EncodingNotSupportedException(string encodingName, Exception innerException) {}
    public EncodingNotSupportedException(string encodingName, string message) {}
    public EncodingNotSupportedException(string encodingName, string message, Exception innerException) {}

    public string EncodingName { get; }

    [Obsolete("SYSLIB0051: Legacy serialization support APIs are obsolete")]
    public override void GetObjectData(SerializationInfo info, StreamingContext context) {}
  }

  [TypeForwardedFrom("Smdn, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null")]
  public static class EncodingUtils {
    public static Encoding GetEncoding(string name, IReadOnlyDictionary<string, int>? codePageCollationTable, EncodingSelectionCallback? selectFallbackEncoding) {}
    public static Encoding? GetEncoding(string name) {}
    public static Encoding? GetEncoding(string name, EncodingSelectionCallback? selectFallbackEncoding) {}
    public static Encoding GetEncodingThrowException(string name) {}
    public static Encoding GetEncodingThrowException(string name, EncodingSelectionCallback? selectFallbackEncoding) {}
    public static bool TryGetEncoding(string? name, IReadOnlyDictionary<string, int>? codePageCollationTable, EncodingSelectionCallback? selectFallbackEncoding, [NotNullWhen(true)] out Encoding? encoding) {}
  }
}
// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.7.1.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.5.0.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
