// Smdn.MSBuild.DefineConstants.NETSdkApi-1.1.1
//   Name: Smdn.MSBuild.DefineConstants.NETSdkApi
//   InformationalVersion: 1.1.1

// List of symbols defined on target framework 'net45'
#define SYSTEM_ARRAY_CONVERTALL
#define SYSTEM_CONVERTER
#define SYSTEM_DIAGNOSTICS_PROCESS
#define SYSTEM_EXCEPTION_CTOR_SERIALIZATIONINFO
#define SYSTEM_ICLONEABLE
#define SYSTEM_IO_STREAM_CLOSE
#define SYSTEM_MATH_DIVREM
#define SYSTEM_NET_NETWORKINFORMATION_PHYSICALADDRESS
#define SYSTEM_RUNTIME_SERIALIZATION_FORMATTER_BINARY
#define SYSTEM_RUNTIME_SERIALIZATION_SERIALIZATIONBINDER
#define SYSTEM_SECURITY_CRYPTOGRAPHY_HASHALGORITHM_CLEAR
#define SYSTEM_TEXT_ENCODING_DEFAULT_ANSI
