// Smdn.MSBuild.DefineConstants.NETSdkApi-1.2.1
//   Name: Smdn.MSBuild.DefineConstants.NETSdkApi
//   InformationalVersion: 1.2.1

// List of symbols defined on target framework 'net452'
#define SYSTEM_ARRAY_CONVERTALL // System.Array.ConvertAll (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_CONVERTER // System.Converter (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_ENVIRONMENT_IS64BITOPERATINGSYSTEM // System.Environment.Is64BitOperatingSystem (NET40_OR_GREATER || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_ENVIRONMENT_IS64BITPROCESS // System.Environment.Is64BitProcess (NET40_OR_GREATER || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_ENVIRONMENT_VERSION // System.Environment.Version (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_EXCEPTION_CTOR_SERIALIZATIONINFO // System.Exception.ctor(SerializationInfo) (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_ICLONEABLE // System.ICloneable (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_MATH_DIVREM // System.Math.DivRem (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_URI_URISCHEMEFILE // System.Uri.UriSchemeFile (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_URI_URISCHEMEHTTP // System.Uri.UriSchemeHttp (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_URI_URISCHEMEHTTPS // System.Uri.UriSchemeHttps (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_URI_URISCHEMEMAILTO // System.Uri.UriSchemeMailto (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_DIAGNOSTICS_PROCESS // System.Diagnostics.Process (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_IO_STREAM_CLOSE // System.IO.Stream.Close (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_NET_NETWORKINFORMATION_PHYSICALADDRESS // System.Net.NetworkInformation.PhysicalAddress (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_RUNTIME_INTEROPSERVICES_MEMORYMARSHAL // System.Runtime.InteropServices.MemoryMarshal (NET45_OR_GREATER || NETSTANDARD1_1_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_RUNTIME_SERIALIZATION_SERIALIZATIONBINDER // System.Runtime.Serialization.SerializationBinder (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_RUNTIME_SERIALIZATION_FORMATTER_BINARY // System.Runtime.Serialization.Formatter.Binary (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_SECURITY_CRYPTOGRAPHY_HASHALGORITHM_CLEAR // System.Security.Cryptography.HashAlgorithm.Clear (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_TEXT_ENCODING_BODYNAME // System.Text.Encoding.BodyName (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_TEXT_ENCODING_DEFAULT_ANSI // System.Text.Encoding.Default_ANSI (NETFRAMEWORK)
