// Smdn.MSBuild.DefineConstants.NETSdkApi-1.2.0
//   Name: Smdn.MSBuild.DefineConstants.NETSdkApi
//   InformationalVersion: 1.2.0

// List of symbols defined on target framework 'net471'
#define SYSTEM_ARRAY_CONVERTALL // System.Array.ConvertAll (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_ARRAY_EMPTY // System.Array.Empty (NET46_OR_GREATER || NETSTANDARD1_3_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_CONVERTER // System.Converter (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_EXCEPTION_CTOR_SERIALIZATIONINFO // System.Exception.ctor(SerializationInfo) (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_FORMATTABLESTRING // System.FormattableString (NET46_OR_GREATER || NETSTANDARD1_3_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_IASYNCDISPOSABLE // System.IAsyncDisposable (NET461_OR_GREATER || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_ICLONEABLE // System.ICloneable (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_MATH_DIVREM // System.Math.DivRem (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_DIAGNOSTICS_PROCESS // System.Diagnostics.Process (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_IO_STREAM_CLOSE // System.IO.Stream.Close (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_NET_NETWORKINFORMATION_PHYSICALADDRESS // System.Net.NetworkInformation.PhysicalAddress (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_RUNTIME_SERIALIZATION_SERIALIZATIONBINDER // System.Runtime.Serialization.SerializationBinder (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_RUNTIME_SERIALIZATION_FORMATTER_BINARY // System.Runtime.Serialization.Formatter.Binary (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_SECURITY_CRYPTOGRAPHY_HASHALGORITHM_CLEAR // System.Security.Cryptography.HashAlgorithm.Clear (NETFRAMEWORK || NETSTANDARD2_0_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_TEXT_ENCODING_DEFAULT_ANSI // System.Text.Encoding.Default_ANSI (NETFRAMEWORK)
#define SYSTEM_THREADING_TASKS_TASK_COMPLETEDTASK // System.Threading.Tasks.Task.CompletedTask (NET46_OR_GREATER || NETSTANDARD1_3_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_THREADING_TASKS_TASK_FROMCANCELED // System.Threading.Tasks.Task.FromCanceled (NET46_OR_GREATER || NETSTANDARD1_3_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
