// Smdn.MSBuild.DefineConstants.NETSdkApi-1.2.1
//   Name: Smdn.MSBuild.DefineConstants.NETSdkApi
//   InformationalVersion: 1.2.1

// List of symbols defined on target framework 'netcoreapp1.0'
#define SYSTEM_ARRAY_EMPTY // System.Array.Empty (NET46_OR_GREATER || NETSTANDARD1_3_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_FORMATTABLESTRING // System.FormattableString (NET46_OR_GREATER || NETSTANDARD1_3_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_RUNTIME_INTEROPSERVICES_MEMORYMARSHAL // System.Runtime.InteropServices.MemoryMarshal (NET45_OR_GREATER || NETSTANDARD1_1_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_THREADING_TASKS_TASK_COMPLETEDTASK // System.Threading.Tasks.Task.CompletedTask (NET46_OR_GREATER || NETSTANDARD1_3_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_THREADING_TASKS_TASK_FROMCANCELED // System.Threading.Tasks.Task.FromCanceled (NET46_OR_GREATER || NETSTANDARD1_3_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
