// Smdn.MSBuild.DefineConstants.NETSdkApi-1.8.0
//   Name: Smdn.MSBuild.DefineConstants.NETSdkApi
//   InformationalVersion: 1.8.0

// List of symbols defined on target framework 'netstandard1.0'
#define SYSTEM_ENUM_TRYPARSE_OF_TENUM // System.Enum.TryParse<TEnum> (NET5_0_OR_GREATER || NETSTANDARD1_0_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NETFRAMEWORK)
#define SYSTEM_ENVIRONMENT_CURRENTMANAGEDTHREADID // System.Environment.CurrentManagedThreadId (NET5_0_OR_GREATER || NETSTANDARD1_0_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NETFRAMEWORK)
#define SYSTEM_STRING_INDEXOF_STRING_STRINGCOMPARISON // System.String.IndexOf(string,StringComparison) (NET5_0_OR_GREATER || NETSTANDARD1_0_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NETFRAMEWORK)
#define SYSTEM_TYPE_GETGENERICTYPEDEFINITION // System.Type.GetGenericTypeDefinition (NET5_0_OR_GREATER || NETSTANDARD1_0_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NETFRAMEWORK)
#define SYSTEM_TYPE_MAKEGENERICTYPE // System.Type.MakeGenericType (NET5_0_OR_GREATER || NETSTANDARD1_0_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NETFRAMEWORK)
#define SYSTEM_NUMERICS_VECTOR // System.Numerics.Vector (NET5_0_OR_GREATER || NETSTANDARD1_0_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NETFRAMEWORK)
#define SYSTEM_REFLECTION_CUSTOMATTRIBUTEEXTENSIONS // System.Reflection.CustomAttributeExtensions (NET5_0_OR_GREATER || NETSTANDARD1_0_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NETFRAMEWORK)
#define SYSTEM_THREADING_TASKS_TASK_FROMRESULT // System.Threading.Tasks.Task.FromResult (NET5_0_OR_GREATER || NETSTANDARD1_0_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NETFRAMEWORK)
