// Smdn.MSBuild.DefineConstants.NETSdkApi-1.5.0
//   Name: Smdn.MSBuild.DefineConstants.NETSdkApi
//   InformationalVersion: 1.5.0

// List of symbols defined on target framework 'netstandard1.0'
#define SYSTEM_ENUM_TRYPARSE_OF_TENUM // System.Enum.TryParse<TEnum> (NETFRAMEWORK || NETSTANDARD1_0_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_ENVIRONMENT_CURRENTMANAGEDTHREADID // System.Environment.CurrentManagedThreadId (NETFRAMEWORK || NETSTANDARD1_0_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_STRING_INDEXOF_STRING_STRINGCOMPARISON // System.String.IndexOf(string,StringComparison) (NETFRAMEWORK || NETSTANDARD1_0_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_TYPE_GETGENERICTYPEDEFINITION // System.Type.GetGenericTypeDefinition (NETFRAMEWORK || NETSTANDARD1_0_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_TYPE_MAKEGENERICTYPE // System.Type.MakeGenericType (NETFRAMEWORK || NETSTANDARD1_0_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_NUMERICS_VECTOR // System.Numerics.Vector (NETFRAMEWORK || NETSTANDARD1_0_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_REFLECTION_CUSTOMATTRIBUTEEXTENSIONS // System.Reflection.CustomAttributeExtensions (NETFRAMEWORK || NETSTANDARD1_0_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
#define SYSTEM_THREADING_TASKS_TASK_FROMRESULT // System.Threading.Tasks.Task.FromResult (NETFRAMEWORK || NETSTANDARD1_0_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER)
