// Smdn.Test.NUnit.Constraints.dll (Smdn.Test.NUnit.Constraints-4.1.0)
//   Name: Smdn.Test.NUnit.Constraints
//   AssemblyVersion: 4.1.0.0
//   InformationalVersion: 4.1.0+504f70f8787ea5c18b1068c405af660ada6294ee
//   TargetFramework: .NETCoreApp,Version=v8.0
//   Configuration: Release
//   Referenced assemblies:
//     Smdn.Fundamental.ControlPicture, Version=3.0.0.0, Culture=neutral
//     System.Linq, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     System.Memory, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
//     System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//     nunit.framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb

using System;
using NUnit.Framework;
using NUnit.Framework.Constraints;
using Smdn.Test.NUnit.Constraints.Buffers;

namespace Smdn.Test.NUnit.Constraints.Buffers {
  public class Is : Is {
    public static ReadOnlyByteMemoryEqualConstraint EqualTo(Memory<byte> expected) {}
    public static ReadOnlyByteMemoryEqualConstraint EqualTo(ReadOnlyMemory<byte> expected) {}
    public static ReadOnlyByteMemoryEqualConstraint EqualTo(byte[] expected) {}
    public static ReadOnlyMemoryEqualConstraint<T> EqualTo<T>(Memory<T> expected) where T : IEquatable<T> {}
    public static ReadOnlyMemoryEqualConstraint<T> EqualTo<T>(ReadOnlyMemory<T> expected) where T : IEquatable<T> {}
    public static ReadOnlyMemoryEqualConstraint<T> EqualTo<T>(T[] expected) where T : IEquatable<T> {}

    public Is() {}
  }

  public class ReadOnlyByteMemoryEqualConstraint : EqualConstraint {
    public ReadOnlyByteMemoryEqualConstraint(ReadOnlyMemory<byte> expected) {}

    public override string Description { get; }
    public ReadOnlyMemory<byte> Expected { get; }

    public override ConstraintResult ApplyTo<TActual>(TActual actual) {}
  }

  public class ReadOnlyByteMemoryEqualConstraintResult : EqualConstraintResult {
    public ReadOnlyByteMemoryEqualConstraintResult(ReadOnlyByteMemoryEqualConstraint constraint, object actual, bool hasSucceeded) {}

    public override void WriteMessageTo(MessageWriter writer) {}
  }

  public class ReadOnlyMemoryEqualConstraintResult<T> : EqualConstraintResult where T : IEquatable<T> {
    public ReadOnlyMemoryEqualConstraintResult(ReadOnlyMemoryEqualConstraint<T> constraint, object actual, bool hasSucceeded) {}

    public override void WriteMessageTo(MessageWriter writer) {}
  }

  public class ReadOnlyMemoryEqualConstraint<T> : EqualConstraint where T : IEquatable<T> {
    public ReadOnlyMemoryEqualConstraint(ReadOnlyMemory<T> expected) {}

    public override string Description { get; }
    public ReadOnlyMemory<T> Expected { get; }

    public override ConstraintResult ApplyTo<TActual>(TActual actual) {}
  }
}
// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.4.1.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.3.1.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
