// SPDX-FileCopyrightText: 2022 smdn <smdn@smdn.jp>
// SPDX-License-Identifier: MIT
#if NETFRAMEWORK || NETCOREAPP3_0_OR_GREATER || NET5_0_OR_GREATER
  // NET10_OR_GREATER
  #if !SYSTEM_ACTIVATOR_CREATEINSTANCE_ASSEMBLYNAME_TYPENAME
    #error "SYSTEM_ACTIVATOR_CREATEINSTANCE_ASSEMBLYNAME_TYPENAME is not defined"
  #endif
#endif
