// SPDX-FileCopyrightText: 2022 smdn <smdn@smdn.jp>
// SPDX-License-Identifier: MIT
#if NETFRAMEWORK || NETSTANDARD1_5_OR_GREATER || NETCOREAPP1_0_OR_GREATER || NET5_0_OR_GREATER
  // NET10_OR_GREATER
  #if !SYSTEM_REFLECTION_ICUSTOMATTRIBUTEPROVIDER
    #error "SYSTEM_REFLECTION_ICUSTOMATTRIBUTEPROVIDER is not defined"
  #endif
#endif
