// Smdn.Fundamental.Null.dll (Smdn.Fundamental.Null-1.0.0-unreleased)
//   Name: Smdn.Fundamental.Null
//   AssemblyVersion: 1.0.0.0
//   InformationalVersion: 1.0.0-unreleased+8bb0a6de6f12c808bd9e96811dedd37cab2f495e
//   TargetFramework: 
//   Configuration: Release
//   Referenced assemblies:
//     System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
#nullable enable annotations

// API list generated by Smdn.Reflection.ReverseGenerating.ListApi.MSBuild.Tasks v1.6.0.0.
// Smdn.Reflection.ReverseGenerating.ListApi.Core v1.4.0.0 (https://github.com/smdn/Smdn.Reflection.ReverseGenerating)
