# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: "2024 smdn <smdn@smdn.jp>"

name: Publish release manual dispatcher

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "The name of the tag for the release to be created."
        required: true
        type: string

      release_note_url:
        description: "The URL of Gist where the release note for the package has been published."
        required: true
        type: string

      release_prerelease:
        description: "The boolean value that indicates whether the release should be published as a prerelease or not."
        required: false
        type: boolean
        default: false

      release_draft:
        description: "The boolean value that indicates whether the release should be published as a draft or not."
        required: false
        type: boolean
        default: false

      package_id:
        description: "The ID of the released package."
        required: true
        type: string

      package_version:
        description: "The version of the released package in SemVer format."
        required: true
        type: string

      package_branch:
        description: "The name of the branch from which the released package was generated."
        required: true
        type: string

      package_prevver_tag:
        description: "The name of the tag that identifies the previous version of the released package."
        required: false
        type: string
        default: ''

      package_available_nuget_org:
        description: "The boolean value that indicates whether the released package has been pushed to NuGet.org or not."
        required: false
        type: boolean
        default: true

      dry_run:
        description: "If true, performs a trial run."
        required: false
        type: boolean
        default: false

jobs:
  run-publish-release:
    name: Publish release for '${{ inputs.release_tag }}'
    uses: smdn/Smdn.Fundamentals/.github/workflows/publish-release.yml@workflows/release-target/v1.11.0
    with:
      workflow_runs_on:             'ubuntu-latest'
      release_tag:                  ${{ inputs.release_tag }}
      release_note_url:             ${{ inputs.release_note_url }}
      release_prerelease:           ${{ inputs.release_prerelease }}
      release_draft:                ${{ inputs.release_draft }}
      package_id:                   ${{ inputs.package_id }}
      package_version:              ${{ inputs.package_version }}
      package_branch:               ${{ inputs.package_branch }}
      package_prevver_tag:          ${{ inputs.package_prevver_tag }}
      package_available_nuget_org:  ${{ inputs.package_available_nuget_org }}
      dry_run:                      ${{ inputs.dry_run }}
    secrets:
      token_gist:                   ${{ secrets.PUBLISH_NEW_RELEASE }}
      token_new_release:            ${{ secrets.PUBLISH_NEW_RELEASE }}
