# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: "2022 smdn <smdn@smdn.jp>"

name: Publish release target

on:
  pull_request:
    types: [closed]

jobs:
  run-publish-release-target:
    uses: smdn/Smdn.Fundamentals/.github/workflows/publish-release-target.yml@workflows/release-target-v1.1.2
    if: (github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/'))
    with:
      pr_number_request_for_release: ${{ github.event.pull_request.number }}
    secrets:
      token_github: ${{ secrets.PUBLISH_NEW_RELEASE }}
      token_nuget_org: ${{ secrets.PUBLISH_PACKAGE_NUGETORG }}
      token_github_packages: ${{ secrets.PUBLISH_NEW_RELEASE }}
