# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: "2022 smdn <smdn@smdn.jp>"

name: Run tests with released packages

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      project:
        description: "The project name to run the test."
        required: false
        type: string
      os:
        description: "The OS label which run the test on. (ex: ubuntu-latest, windows-latest, macos-latest)"
        required: false
        type: string
      verbose:
        description: "If true, enables verbose output."
        required: false
        type: boolean
        default: false

jobs:
  # If the workflow is triggered by 'release' event,
  # wait for a while until the package is published on NuGet
  defer-until-publish-package:
    name: Delay until the package is published
    runs-on: ubuntu-latest
    steps:
    - name: Wait for a while
      run: |
        if [ '${{ github.event_name }}' = 'release' ]; then
          sleep 5.0m
        fi

  run-test:
    uses: smdn/Smdn.Fundamentals/.github/workflows/test.yml@workflows/test-v1.0.5
    needs: defer-until-publish-package
    with:
      project:              ${{ github.event.inputs.project }}
      os:                   ${{ github.event.inputs.os }}
      extra_options_common: '/p:TestReleasedPackage=true'
      verbose:              ${{ fromJSON(github.event.inputs.verbose) }}
      dotnet_sdk_version:   '6.0.200'
      timeout_hang:               "[ {'OS':'windows','Timeout':'6min'}, {'OS':'macos','Timeout':'3min'}, {'OS':'','Timeout':'1min'} ]"
      timeout_vstest_connection:  "[ {'OS':'windows','Timeout':360}, {'OS':'macos','Timeout':180}, {'OS':'','Timeout':60} ]"
    secrets:
      token_repo: ${{ secrets.GITHUB_TOKEN }}
